// Mock data for PSPS Main Summary Page
// Based on Section 5 Functional Requirements for Release 1

export const mockMETModels = [
  { id: '00z-2024-02-11', label: '00z (Feb 11, 2024)', timestamp: '2024-02-11T19:30:00Z', version: '00z' },
  { id: '12z-2024-02-11', label: '12z (Feb 11, 2024)', timestamp: '2024-02-11T07:30:00Z', version: '12z' },
];

export const mockTransmissionLines = [
  {
    id: 'TL-001',
    tp_name: 'TP_North_Alpha',
    tline_name: 'N-Fresno-42kV',
    sap_func_loc: 'LOC-001-42',
    max_ws: 42,
    max_wg: 68,
    fpc_count: 3,
    cfpt_asset_count: 5,
    cfpt_veg_count: 2,
    cfb_count: 1,
    open_a_tags: 2,
    open_hni_hnu: 1,
    direct_type: 'D',
    met_scope_version: 'v1.0',
    max_oa_pf: 0.78,
    min_rh_2m: 18,
    min_dfm_10hr: 90,
    min_ndvi: 0.42,
    flags: { isNearGuidance: true, hasDirectImpact: false, isDINDR: false },
    structures: [
      {
        id: 'S-001-A',
        name: 'Structure 42-A1',
        oa_pf: 0.78,
        ignition_probability: 0.65,
        cfpt_asset: true,
        cfpt_veg: false,
        open_a_tag: 'A-Safety-001',
        hni_hnu_tags: [],
        vm_tags: ['VM-HNI-Emergency'],
        notes: '',
        overrides: [],
      },
      {
        id: 'S-001-B',
        name: 'Structure 42-A2',
        oa_pf: 0.62,
        ignition_probability: 0.48,
        cfpt_asset: true,
        cfpt_veg: true,
        open_a_tag: null,
        hni_hnu_tags: ['HNU-Maintenance'],
        vm_tags: [],
        notes: '',
        overrides: [],
      },
      {
        id: 'S-001-C',
        name: 'Structure 42-A3',
        oa_pf: 0.55,
        ignition_probability: 0.42,
        cfpt_asset: true,
        cfpt_veg: false,
        open_a_tag: null,
        hni_hnu_tags: [],
        vm_tags: [],
        notes: 'Pre-patrol completed - no issues',
        overrides: [
          {
            user: 'jane.smith@utilities.ca',
            timestamp: '2024-02-11T15:22:00Z',
            action: 'marked_reviewed',
            before: 'D',
            after: 'D',
            reason: 'Field inspection completed',
          },
        ],
      },
    ],
    geoPoint: { lat: 37.3382, lng: -119.8863 },
  },
  {
    id: 'TL-002',
    tp_name: 'TP_Central_Beta',
    tline_name: 'C-Kern-69kV',
    sap_func_loc: 'LOC-002-69',
    max_ws: 55,
    max_wg: 82,
    fpc_count: 7,
    cfpt_asset_count: 12,
    cfpt_veg_count: 8,
    cfb_count: 3,
    open_a_tags: 4,
    open_hni_hnu: 2,
    direct_type: 'D',
    met_scope_version: 'v1.0',
    max_oa_pf: 0.89,
    min_rh_2m: 12,
    min_dfm_10hr: 75,
    min_ndvi: 0.28,
    flags: { isNearGuidance: true, hasDirectImpact: true, isDINDR: false },
    structures: [
      {
        id: 'S-002-A',
        name: 'Structure 69-B1',
        oa_pf: 0.89,
        ignition_probability: 0.78,
        cfpt_asset: true,
        cfpt_veg: true,
        open_a_tag: 'A-Critical-042',
        hni_hnu_tags: ['HNI-Hazard'],
        vm_tags: ['VM-HNI-Emergency', 'VM-Priority-1'],
        notes: 'Critical vegetation removal required',
        overrides: [],
      },
      {
        id: 'S-002-B',
        name: 'Structure 69-B2',
        oa_pf: 0.76,
        ignition_probability: 0.65,
        cfpt_asset: true,
        cfpt_veg: true,
        open_a_tag: null,
        hni_hnu_tags: ['HNU-Maintenance'],
        vm_tags: [],
        notes: '',
        overrides: [],
      },
    ],
    geoPoint: { lat: 35.3733, lng: -119.0187 },
  },
  {
    id: 'TL-003',
    tp_name: 'TP_South_Gamma',
    tline_name: 'S-Tulare-115kV',
    sap_func_loc: 'LOC-003-115',
    max_ws: 38,
    max_wg: 56,
    fpc_count: 2,
    cfpt_asset_count: 2,
    cfpt_veg_count: 0,
    cfb_count: 0,
    open_a_tags: 0,
    open_hni_hnu: 0,
    direct_type: 'D',
    met_scope_version: 'v1.0',
    max_oa_pf: 0.43,
    min_rh_2m: 26,
    min_dfm_10hr: 125,
    min_ndvi: 0.61,
    flags: { isNearGuidance: false, hasDirectImpact: false, isDINDR: false },
    structures: [
      {
        id: 'S-003-A',
        name: 'Structure 115-C1',
        oa_pf: 0.43,
        ignition_probability: 0.28,
        cfpt_asset: true,
        cfpt_veg: false,
        open_a_tag: null,
        hni_hnu_tags: [],
        vm_tags: [],
        notes: '',
        overrides: [],
      },
    ],
    geoPoint: { lat: 36.1699, lng: -119.4944 },
  },
  {
    id: 'TL-004',
    tp_name: 'TP_East_Delta',
    tline_name: 'E-Kings-42kV',
    sap_func_loc: 'LOC-004-42',
    max_ws: 48,
    max_wg: 71,
    fpc_count: 4,
    cfpt_asset_count: 6,
    cfpt_veg_count: 3,
    cfb_count: 2,
    open_a_tags: 1,
    open_hni_hnu: 1,
    direct_type: 'DINDR',
    met_scope_version: 'v1.0',
    max_oa_pf: 0.81,
    min_rh_2m: 15,
    min_dfm_10hr: 88,
    min_ndvi: 0.35,
    flags: { isNearGuidance: true, hasDirectImpact: true, isDINDR: true },
    structures: [
      {
        id: 'S-004-A',
        name: 'Structure 42-D1',
        oa_pf: 0.81,
        ignition_probability: 0.72,
        cfpt_asset: true,
        cfpt_veg: true,
        open_a_tag: 'A-Review-105',
        hni_hnu_tags: ['HNI-Hazard'],
        vm_tags: ['VM-HNI-Emergency'],
        notes: 'Grounding recommended - high OA',
        overrides: [
          {
            user: 'mike.chen@utilities.ca',
            timestamp: '2024-02-11T14:15:00Z',
            action: 'changed_to_dindr',
            before: 'D',
            after: 'DINDR',
            reason: 'Engineering assessment - grounding necessary',
          },
        ],
      },
    ],
    geoPoint: { lat: 35.8691, lng: -119.6188 },
  },
  {
    id: 'TL-005',
    tp_name: 'TP_West_Echo',
    tline_name: 'W-Inyo-34.5kV',
    sap_func_loc: 'LOC-005-34',
    max_ws: 52,
    max_wg: 75,
    fpc_count: 5,
    cfpt_asset_count: 8,
    cfpt_veg_count: 4,
    cfb_count: 2,
    open_a_tags: 2,
    open_hni_hnu: 1,
    direct_type: 'D',
    met_scope_version: 'v1.0',
    max_oa_pf: 0.72,
    min_rh_2m: 19,
    min_dfm_10hr: 92,
    min_ndvi: 0.38,
    flags: { isNearGuidance: true, hasDirectImpact: false, isDINDR: false },
    structures: [
      {
        id: 'S-005-A',
        name: 'Structure 34-E1',
        oa_pf: 0.72,
        ignition_probability: 0.58,
        cfpt_asset: true,
        cfpt_veg: true,
        open_a_tag: null,
        hni_hnu_tags: [],
        vm_tags: [],
        notes: '',
        overrides: [],
      },
    ],
    geoPoint: { lat: 37.2952, lng: -118.2551 },
  },
];

export const mockTPPolygons = [
  {
    id: 'TP-001',
    name: 'TP_North_Alpha',
    center: { lat: 37.3382, lng: -119.8863 },
    bounds: {
      north: 37.4,
      south: 37.27,
      east: -119.75,
      west: -120.03,
    },
  },
  {
    id: 'TP-002',
    name: 'TP_Central_Beta',
    center: { lat: 35.3733, lng: -119.0187 },
    bounds: {
      north: 35.45,
      south: 35.30,
      east: -118.90,
      west: -119.15,
    },
  },
  {
    id: 'TP-003',
    name: 'TP_South_Gamma',
    center: { lat: 36.1699, lng: -119.4944 },
    bounds: {
      north: 36.30,
      south: 36.05,
      east: -119.35,
      west: -119.65,
    },
  },
  {
    id: 'TP-004',
    name: 'TP_East_Delta',
    center: { lat: 35.8691, lng: -119.6188 },
    bounds: {
      north: 35.95,
      south: 35.78,
      east: -119.50,
      west: -119.75,
    },
  },
  {
    id: 'TP-005',
    name: 'TP_West_Echo',
    center: { lat: 37.2952, lng: -118.2551 },
    bounds: {
      north: 37.40,
      south: 37.19,
      east: -118.15,
      west: -118.36,
    },
  },
];

export const mockATagPoints = [
  { id: 'A-001', name: 'A-Safety-001', lat: 37.3380, lng: -119.8860, severity: 'medium' },
  { id: 'A-002', name: 'A-Critical-042', lat: 35.3735, lng: -119.0185, severity: 'high' },
  { id: 'A-003', name: 'A-Review-105', lat: 35.8693, lng: -119.6190, severity: 'high' },
];

export const mockHNIHNUPoints = [
  { id: 'HNI-001', name: 'HNI-Hazard', lat: 35.3730, lng: -119.0190, type: 'HNI' },
  { id: 'HNU-001', name: 'HNU-Maintenance', lat: 37.3385, lng: -119.8865, type: 'HNU' },
  { id: 'HNI-002', name: 'HNI-Hazard', lat: 35.8690, lng: -119.6185, type: 'HNI' },
];

export const mockAppState = {
  currentMETModel: '00z-2024-02-11',
  currentMETTimestamp: new Date('2024-02-11T19:30:00Z'),
  lastRefreshTime: new Date(Date.now() - 8 * 60000), // 8 minutes ago
  isRefreshStale: false, // will be true if > 15 minutes
  viewMode: 'All', // 'All', 'DirectScope', 'Removed'
  selectedLineId: 'TL-001',
  selectedStructureId: 'S-001-A',
  filters: {
    region: null,
    psps_mfpc: 'All', // 'All', 'Minimum', 'Near'
    guidance_type: [], // ['CFPt-Asset', 'CFPt-Veg', 'CFB']
    open_a_tags: false,
    open_hni_hnu: false,
  },
  layerVisibility: {
    transmissionLines: true,
    structures: true,
    tpPolygons: true,
    hfra: false,
    hfraShading: false,
    vmTags: true,
    aTags: true,
  },
  snapshots: [
    {
      id: 'snap-001',
      timestamp: '2024-02-11T18:22:00Z',
      version: '00z-2024-02-11',
      name: 'Pre-Briefing Review v1',
      lineCount: 5,
      directImpactCount: 2,
      dindirCount: 1,
    },
    {
      id: 'snap-002',
      timestamp: '2024-02-11T16:45:00Z',
      version: '12z-2024-02-10',
      name: 'Field Inspection Summary',
      lineCount: 5,
      directImpactCount: 2,
      dindirCount: 0,
    },
  ],
};

export const generateTableData = () => {
  return mockTransmissionLines.map((line) => ({
    ...line,
    guidanceTags: [],
    tags: {
      cfptAsset: line.cfpt_asset_count > 0,
      cfptVeg: line.cfpt_veg_count > 0,
      cfb: line.cfb_count > 0,
      openA: line.open_a_tags > 0,
      openHNI: line.open_hni_hnu > 0,
    },
  }));
};

export const mockMetadata = {
  eventName: 'Diablo Wind Event - Feb 11-12, 2024',
  eventVersion: 'v2',
  lastMETRunTime: '2024-02-11T19:30:00Z',
  nextExpectedRefresh: '2024-02-11T20:30:00Z',
  userInfo: {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@utilities.ca',
    role: 'PSPS Coordinator',
  },
};
